theme = "onedark"

[editor]
line-number = "relative"
true-color = true
rulers = [80,120]
color-modes = true
bufferline = "multiple"
popup-border = "all"
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
undercurl = true
auto-completion = true
soft-wrap.enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name" ]
right = ["diagnostics", "separator", "workspace-diagnostics", "selections", "position", "total-line-numbers"]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }
C-s = [":write", "normal_mode"]
A-h = "move_char_left"
A-l = "move_char_right"
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal]
ret = "goto_word"
A-j = ["extend_to_line_bounds","delete_selection","paste_after","select_mode", "goto_line_start", "normal_mode"]
A-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "flip_selections"]
K = "hover"
g = { a = "code_action" }
S-right = "extend_char_right"
S-left = "extend_char_left"
S-up = "extend_line_up"
S-down = "extend_line_down"
space = { x = ":buffer-close"}
C-right = [ "move_next_word_start", "move_char_left", "move_char_right" ]
C-left = [ "move_prev_word_start", "move_char_left", "move_char_right" ]
C-s = ["save_selection", ":w"]
C-q = ":quit!"
R = ":config-reload"
C-f = ":config-open"
"$" = "extend_to_line_end"
"^" = "extend_to_line_start"
tab = ":buffer-next"
S-tab = ":buffer-previous"
y = ["yank", ":clipboard-yank"]
G = ["goto_last_line", "goto_line_end"]
C-o = "flip_selections"

[keys.select]
y = ["yank", ":clipboard-yank"]
G = ["goto_last_line", "goto_line_end"]
C-o = "flip_selections"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1
