# TOML

[[language]]
name = "toml"
auto-format = true

[language.formatter]
command = "taplo"
args = ["format", "-"]

# Bash

[[language]]
name = "bash"
language-servers = ["bash-language-server"]
formatter = { command = "shfmt", args = ["-i", "4"] }
auto-format = true

# Go

[[language]]
name = "go"
language-servers = ["gopls"]

[language.formatter]
command = "goimports"

# Lua

[[language]]
name = "lua"
auto-format = true

# HTML

[[language]]
auto-format = false
name = "html"

[language.formatter]
args = ["--parser", "html", "--tab-width", "2"]
command = "prettier"

[language.indent]
tab-width = 2
unit = " "

# CSS

[[language]]
language-servers = ["css-languageserver", "copilot"]
name = "css"

[language.formatter]
args = ["--parser", "css", "--tab-width", "2"]
command = "prettier"

[language.indent]
tab-width = 4
unit = " "

# Typescript

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server"]

[language.formatter]
args = ["--parser", "typescript", "--tab-width", "4"]
command = "prettier"

[language.indent]
tab-width = 4
unit = " "

# SVG

[[language]]
file-types = ["svg"]
name = "svg"
roots = []
scope = ""

[language.formatter]
args = ["--pretty", "-"]
command = "svgo"
